"""Apply generated alt texts to all CYBERINFRA PPTX files."""
import os, sys, json
sys.path.insert(0, os.path.dirname(__file__))
from fix_office import apply_pptx_alt_texts

BASE = "c:/Users/alima/OneDrive - University of South Carolina/Research/Working Directory/Blackboard_Accessibility_report/course_content/CYBERINFRA-FALL-2025"

files_alts = {
    os.path.join(BASE, "Module 2 - Measuring Security", "Lec2.pptx"): [
        {"slide": 11, "shape_idx": 2, "alt_text": "TCSEC Summary table showing Security Policy requirements with black and gray cells indicating feature applicability across six evaluation levels."},
        {"slide": 11, "shape_idx": 3, "alt_text": "TCSEC Summary continuation showing Documentation and Legend sections with feature requirements mapped across evaluation levels."},
        {"slide": 12, "shape_idx": 2, "alt_text": "TCSEC Summary table showing Security Policy section with features like Discretionary Access Control and Mandatory Access Control."},
        {"slide": 12, "shape_idx": 3, "alt_text": "TCSEC Summary table highlighting Accountability section requirements including Audit Trails and User Identification."},
        {"slide": 12, "shape_idx": 4, "alt_text": "TCSEC Summary table showing Assurance and Documentation sections with Design Verification and Configuration Management."},
        {"slide": 13, "shape_idx": 1, "alt_text": "TCSEC Summary table displaying Security Policy section with discretionary and mandatory access control features."},
        {"slide": 13, "shape_idx": 2, "alt_text": "TCSEC Summary table showing Documentation and Legend sections with requirements for Design Analysis and Trusted Distribution."},
        {"slide": 14, "shape_idx": 2, "alt_text": "TCSEC Summary table with Accountability section featuring User Identification, Audit Trail, and Secure Message Recovery."},
        {"slide": 14, "shape_idx": 3, "alt_text": "TCSEC Summary table showing Security Policy requirements including Discretionary Access Control and Object Reuse."},
        {"slide": 14, "shape_idx": 4, "alt_text": "TCSEC Summary table displaying Assurance and Documentation sections with Design Analysis and Configuration Management."},
        {"slide": 38, "shape_idx": 3, "alt_text": "Capability Levels diagram showing six nested ovals representing maturity levels 0 through 5, from Not Performed through Continuously Improving."},
    ],
    os.path.join(BASE, "Module 3 - Threat Modeling", "F24-DSci523-Lec3(1).pptx"): [
        {"slide": 8, "shape_idx": 3, "alt_text": "Attack tree diagram showing RFID Denial of Service as root goal with six sub-attacks including Remove Tag, Disable Tag, and Block Communication."},
        {"slide": 13, "shape_idx": 3, "alt_text": "XKCD comic showing two scenarios: a cryptographer failing to crack encryption versus using a wrench to get the password."},
        {"slide": 19, "shape_idx": 3, "alt_text": "Attack-defense tree with Block Communication as root, branching into attack vectors in red and defensive countermeasures in green."},
        {"slide": 22, "shape_idx": 3, "alt_text": "Screenshot of ADTool software interface showing a visual attack-defense tree diagram with red and yellow oval nodes."},
        {"slide": 52, "shape_idx": 2, "alt_text": "Microsoft Threat Modeling diagram showing a data flow architecture with processes and trust boundary connected via HTTPS."},
    ],
    os.path.join(BASE, "Module 4 - Structured Design", "F24-DSci523-Lec4(1).pptx"): [
        {"slide": 37, "shape_idx": 0, "alt_text": "Text slide listing ALDBD module topics including Module Structure, Active Exception Handling, and Exception Semantics."},
        {"slide": 38, "shape_idx": 1, "alt_text": "Text slide showing Agent Procedure topics covering ALDBD module rules and Configuration Examples."},
        {"slide": 40, "shape_idx": 2, "alt_text": "Table showing program specifications with columns for Program name, Inputs, Outputs, and Exceptions."},
        {"slide": 41, "shape_idx": 2, "alt_text": "Table displaying program specifications for cg.getc and s_ungetc with Inputs, Outputs, and Exceptions."},
        {"slide": 44, "shape_idx": 2, "alt_text": "Java code snippet showing a LoggerBad class with logToFile method that creates a FileWriter."},
        {"slide": 45, "shape_idx": 1, "alt_text": "Java code snippet showing LoggerBad class with logToFile method implementation."},
        {"slide": 46, "shape_idx": 1, "alt_text": "Java code showing a Logger interface with FileLogger and ConsoleLogger implementations."},
        {"slide": 47, "shape_idx": 1, "alt_text": "Java code showing CartBad class with addItemAndCheckout method containing multiple responsibilities."},
        {"slide": 48, "shape_idx": 1, "alt_text": "Java code displaying CartBad class with addItemAndCheckout method and placeholder comments."},
        {"slide": 49, "shape_idx": 1, "alt_text": "Java code showing Cart class with four separate methods demonstrating single responsibility principle."},
        {"slide": 50, "shape_idx": 1, "alt_text": "Java code displaying UserServiceBad class with three unrelated methods violating single responsibility."},
        {"slide": 51, "shape_idx": 1, "alt_text": "Java code showing UserServiceBad class with mixed responsibilities for profiles and marketing."},
        {"slide": 52, "shape_idx": 1, "alt_text": "Java code displaying separate UserProfileService and MarketingService classes following single responsibility."},
        {"slide": 53, "shape_idx": 2, "alt_text": "Java code showing WeatherServiceBad class with direct API dependency for temperature retrieval."},
        {"slide": 54, "shape_idx": 1, "alt_text": "Java code displaying WeatherServiceBad class with tight coupling to OpenWeatherApi."},
        {"slide": 55, "shape_idx": 1, "alt_text": "Java code showing WeatherProvider interface with implementations using dependency injection."},
        {"slide": 56, "shape_idx": 1, "alt_text": "Java code displaying FileUploaderBad class with direct AWS SDK dependency for S3 uploads."},
        {"slide": 57, "shape_idx": 1, "alt_text": "Java code showing FileUploaderBad class with tight coupling to AWS S3 SDK."},
        {"slide": 58, "shape_idx": 1, "alt_text": "Java code displaying Storage interface with S3Storage and LocalStorage implementations."},
    ],
    os.path.join(BASE, "Module 6 - Testing", "F24-DSci523-Lec6-2 (1).pptx"): [
        {"slide": 21, "shape_idx": 1, "alt_text": "Tree diagram showing sign propagation from Top to Bottom nodes with constraint notation."},
        {"slide": 22, "shape_idx": 2, "alt_text": "Code snippet with taint analysis showing variable initialization and conditional assignment."},
        {"slide": 23, "shape_idx": 2, "alt_text": "Taint analysis progression showing variable states after initialization and conditional assignment."},
        {"slide": 24, "shape_idx": 2, "alt_text": "Code snippet with taint analysis tracking states through assignment with three value constraints."},
        {"slide": 25, "shape_idx": 2, "alt_text": "Code snippet with taint analysis and tree diagram showing propagation paths."},
        {"slide": 26, "shape_idx": 2, "alt_text": "Sign propagation tree diagram with numerical constraints showing intervals at different nodes."},
        {"slide": 27, "shape_idx": 2, "alt_text": "Code snippet showing while loop with taint analysis displaying taint state."},
        {"slide": 28, "shape_idx": 2, "alt_text": "Code snippet with loop increment operation and taint analysis showing state transition."},
        {"slide": 1, "shape_idx": 20, "alt_text": "Red italic text reading Testing as a slide title."},
        {"slide": 29, "shape_idx": 2, "alt_text": "Code snippet tracking loop iterations with taint states showing value changes."},
        {"slide": 30, "shape_idx": 2, "alt_text": "Code snippet with loop analysis displaying taint states at iteration boundaries."},
        {"slide": 31, "shape_idx": 2, "alt_text": "Code snippet with loop tracking showing progression of taint states through iterations."},
        {"slide": 32, "shape_idx": 2, "alt_text": "Code snippet with loop analysis showing final taint states after complete execution."},
        {"slide": 33, "shape_idx": 2, "alt_text": "Code snippet explaining optimization to blind iterations to Top after 10 iterations."},
        {"slide": 34, "shape_idx": 2, "alt_text": "Code snippet explaining refinement strategy after reaching a fixed point."},
        {"slide": 35, "shape_idx": 2, "alt_text": "Green-highlighted box about Unassigned Variable with code comparison."},
        {"slide": 37, "shape_idx": 3, "alt_text": "Code snippet showing variable assignment and control flow with goto instruction."},
        {"slide": 38, "shape_idx": 3, "alt_text": "Control flow analysis table showing statements, constraints, and program counter values."},
        {"slide": 38, "shape_idx": 4, "alt_text": "Security vulnerability summary table with CVE descriptions and affected system counts."},
        {"slide": 54, "shape_idx": 1, "alt_text": "Vulnerability table displaying OpenSSH, Samba, and firewall exploit details."},
    ],
    os.path.join(BASE, "Module 7 - Secure Operation", "F24-DSci523-Lec7(1).pptx"): [
        {"slide": 12, "shape_idx": 17, "alt_text": "Text label reading public in dark red font."},
        {"slide": 12, "shape_idx": 19, "alt_text": "Text label reading private in dark red font."},
        {"slide": 12, "shape_idx": 20, "alt_text": "Google Chrome browser icon and label in a blue rounded rectangle."},
        {"slide": 12, "shape_idx": 6, "alt_text": "Google Chrome logo with red, green, yellow, and blue color sections."},
        {"slide": 12, "shape_idx": 7, "alt_text": "Bank of America logo with blue text and red slashed lines symbol."},
        {"slide": 13, "shape_idx": 15, "alt_text": "Text label reading public in dark red font."},
        {"slide": 13, "shape_idx": 17, "alt_text": "Text label reading private in dark red font."},
        {"slide": 13, "shape_idx": 6, "alt_text": "Google Chrome logo with red, green, yellow, and blue color sections."},
        {"slide": 13, "shape_idx": 7, "alt_text": "Bank of America logo with blue text and red slashed lines symbol."},
        {"slide": 14, "shape_idx": 10, "alt_text": "Text label reading public in dark red font."},
        {"slide": 14, "shape_idx": 12, "alt_text": "Text label reading private in dark red font."},
        {"slide": 14, "shape_idx": 2, "alt_text": "Google Chrome browser icon and label in a blue rounded rectangle."},
        {"slide": 16, "shape_idx": 10, "alt_text": "macOS Keychain Access window showing digital certificates from various certification authorities."},
        {"slide": 16, "shape_idx": 9, "alt_text": "macOS Keychain Access window showing digital certificates with names and issue dates."},
        {"slide": 17, "shape_idx": 1, "alt_text": "Text about root key store: every device has one, must not contain malicious certificates."},
        {"slide": 17, "shape_idx": 2, "alt_text": "Text about root key store: every device has one, must not contain malicious certificates."},
        {"slide": 18, "shape_idx": 3, "alt_text": "Certificate chain hierarchy showing Equifax Root CA through GeoTrust intermediate CAs to end-entity certificate."},
        {"slide": 20, "shape_idx": 1, "alt_text": "TLS handshake protocol diagram showing ClientHello, ServerHello, certificate exchange, and session key creation."},
        {"slide": 21, "shape_idx": 3, "alt_text": "Browser address bar showing secure HTTPS connection with green padlock icon."},
        {"slide": 21, "shape_idx": 4, "alt_text": "Browser address bar showing HTTPS connection to twitter.com with green padlock."},
        {"slide": 23, "shape_idx": 3, "alt_text": "Certificate chain hierarchy with root CA and intermediate CAs connected to five digital certificates."},
        {"slide": 26, "shape_idx": 20, "alt_text": "Text label reading Testing in italic dark red font."},
        {"slide": 1, "shape_idx": 20, "alt_text": "Text label reading Testing in italic dark red font."},
        {"slide": 30, "shape_idx": 3, "alt_text": "XML code showing XCCDF rule for Microsoft network server disconnect clients configuration."},
        {"slide": 33, "shape_idx": 20, "alt_text": "Text label reading Testing in italic dark red font."},
        {"slide": 46, "shape_idx": 20, "alt_text": "Text label reading Testing in italic dark red font."},
    ],
    os.path.join(BASE, "Top Level", "Final Review.pptx"): [
        {"slide": 9, "shape_idx": 6, "alt_text": "Google Chrome logo with red, green, yellow, and blue segments."},
        {"slide": 9, "shape_idx": 7, "alt_text": "Bank of America logo with blue text and red parallel lines icon."},
        {"slide": 10, "shape_idx": 6, "alt_text": "Google Chrome logo with red, green, yellow, and blue segments."},
        {"slide": 10, "shape_idx": 7, "alt_text": "Bank of America logo with blue text and red parallel lines icon."},
        {"slide": 13, "shape_idx": 9, "alt_text": "Keychain Access window showing certificate authorities with certificate types and dates."},
        {"slide": 14, "shape_idx": 1, "alt_text": "Keychain Access window displaying certificate authorities including Symantec."},
        {"slide": 15, "shape_idx": 3, "alt_text": "Certificate Authority hierarchy diagram showing root CA, intermediate CAs, and digital certificates."},
        {"slide": 16, "shape_idx": 1, "alt_text": "Network diagram showing client and server with dynamic packet filter and UDP traffic rules."},
        {"slide": 26, "shape_idx": 3, "alt_text": "Access control list showing four permission rules with IP addresses and CIDR notation."},
        {"slide": 29, "shape_idx": 3, "alt_text": "Network diagram with firewall filtering rules showing IP addresses and port designations."},
        {"slide": 30, "shape_idx": 3, "alt_text": "Client server network diagram with Dynamic Packet Filter rules and UDP configuration."},
        {"slide": 32, "shape_idx": 0, "alt_text": "Network diagram showing client and server with dynamic packet filter and traffic rules."},
        {"slide": 33, "shape_idx": 2, "alt_text": "Network security diagram showing firewall blocking zero-day exploit attack."},
        {"slide": 34, "shape_idx": 1, "alt_text": "Sensor network attack diagram showing numbered steps from attacker through cloud to target."},
        {"slide": 35, "shape_idx": 1, "alt_text": "Attack scenario showing attacker connecting through cloud and switch to sensor and console."},
        {"slide": 36, "shape_idx": 1, "alt_text": "Sensor network attack diagram with attacker, cloud, switch, sensor, and target infrastructure."},
        {"slide": 37, "shape_idx": 1, "alt_text": "Network attack path diagram showing attacker to sensor to management console."},
        {"slide": 38, "shape_idx": 1, "alt_text": "Table comparing advantages and disadvantages of IDS and IPS systems."},
        {"slide": 44, "shape_idx": 2, "alt_text": "Network security diagram showing private network with VLAN, firewall, and DNS routing."},
        {"slide": 46, "shape_idx": 19, "alt_text": "Server rack with multiple network port panels and uplink connections."},
        {"slide": 46, "shape_idx": 20, "alt_text": "Computer workstation with blue monitor and keyboard in isometric view."},
        {"slide": 46, "shape_idx": 21, "alt_text": "Laptop computer with blue screen in isometric view."},
        {"slide": 46, "shape_idx": 22, "alt_text": "Server rack with network port panels and status indicators."},
        {"slide": 46, "shape_idx": 23, "alt_text": "Computer workstation with blue monitor in isometric 3D illustration."},
        {"slide": 46, "shape_idx": 25, "alt_text": "Laptop computer with blue screen in isometric 3D view."},
        {"slide": 46, "shape_idx": 30, "alt_text": "Network switch device with multiple connection ports."},
        {"slide": 46, "shape_idx": 31, "alt_text": "Black cloud icon representing cloud computing or network services."},
        {"slide": 47, "shape_idx": 2, "alt_text": "Firewall and NAT diagram showing computer connecting through firewall to internet."},
        {"slide": 47, "shape_idx": 4, "alt_text": "Firewall rule configuration table with source and destination zones."},
        {"slide": 48, "shape_idx": 2, "alt_text": "Firewall rule table displaying egress rules with source and destination columns."},
        {"slide": 49, "shape_idx": 2, "alt_text": "Network diagram showing computer through firewall and NAT to external network."},
        {"slide": 49, "shape_idx": 3, "alt_text": "Firewall configuration rules table with network zone and application details."},
        {"slide": 50, "shape_idx": 2, "alt_text": "Firewall rule table displaying allowed and denied traffic rules."},
        {"slide": 50, "shape_idx": 4, "alt_text": "Application layer security table with required apps and action controls."},
        {"slide": 51, "shape_idx": 0, "alt_text": "Network segmentation diagram with public and private zones and DNS configuration."},
        {"slide": 52, "shape_idx": 1, "alt_text": "SMTP Stages diagram showing application-centric traffic classification."},
        {"slide": 52, "shape_idx": 3, "alt_text": "OSI model layer diagram showing Applications through Physical layers."},
        {"slide": 54, "shape_idx": 1, "alt_text": "Firewall rule configuration table with allow and deny actions."},
        {"slide": 54, "shape_idx": 2, "alt_text": "Firewall and NAT network diagram with computer, firewall, and internet."},
        {"slide": 55, "shape_idx": 1, "alt_text": "Firewall and NAT diagram showing computer connecting to global network."},
        {"slide": 55, "shape_idx": 2, "alt_text": "Network traffic flow diagram showing HTTP/HTTPS communication with protocol shifts."},
        {"slide": 57, "shape_idx": 2, "alt_text": "Monitor and log analysis table showing security monitoring activities."},
        {"slide": 59, "shape_idx": 12, "alt_text": "Server rack icon with horizontal storage drives."},
        {"slide": 59, "shape_idx": 13, "alt_text": "Computer workstation with tower and monitor."},
        {"slide": 59, "shape_idx": 18, "alt_text": "Desktop computer setup with tower and monitor."},
        {"slide": 59, "shape_idx": 4, "alt_text": "Server tower with stacked drives and status indicator."},
        {"slide": 63, "shape_idx": 3, "alt_text": "Concentric circle diagram showing ACLs, Stateful Packet Filters, IDS/IPS, and NGFW layers."},
        {"slide": 68, "shape_idx": 3, "alt_text": "Static malware analysis workflow from identifying type through extracting strings."},
        {"slide": 69, "shape_idx": 3, "alt_text": "Terminal output showing MD5 hash computation and file listing."},
        {"slide": 70, "shape_idx": 3, "alt_text": "VirusTotal interface screenshot showing file analysis options."},
        {"slide": 71, "shape_idx": 3, "alt_text": "Command line output showing strings command on unknown executable."},
        {"slide": 72, "shape_idx": 3, "alt_text": "VBScript malware code with commands for file system operations."},
        {"slide": 73, "shape_idx": 3, "alt_text": "Classroom illustration about monitoring and watching security activities."},
        {"slide": 75, "shape_idx": 0, "alt_text": "Find the difference puzzle with two similar scenes for security awareness."},
        {"slide": 76, "shape_idx": 0, "alt_text": "Surveillance meme illustration representing monitoring concept."},
        {"slide": 78, "shape_idx": 0, "alt_text": "Magnifying glass examining insects representing malware detection."},
        {"slide": 78, "shape_idx": 5, "alt_text": "Illustration comparing bug and feature with two ant-like creatures."},
        {"slide": 79, "shape_idx": 0, "alt_text": "Python honeypot framework output showing profiling and process analysis."},
        {"slide": 79, "shape_idx": 5, "alt_text": "Memory dump analysis output with highlighted IP addresses."},
        {"slide": 88, "shape_idx": 4, "alt_text": "System memory analysis showing process execution with DLL listings."},
        {"slide": 89, "shape_idx": 4, "alt_text": "Malware analysis output showing process creation and network connections."},
        {"slide": 90, "shape_idx": 4, "alt_text": "Memory dump analysis showing executable loading with process IDs."},
        {"slide": 91, "shape_idx": 4, "alt_text": "Dynamic malware analysis output with memory addresses and system calls."},
        {"slide": 92, "shape_idx": 4, "alt_text": "Executable header diagram showing file structure with packing transformation."},
        {"slide": 93, "shape_idx": 4, "alt_text": "Memory contents diagram showing iexplorer.exe with evil.dll highlighted."},
        {"slide": 94, "shape_idx": 0, "alt_text": "Four colored icons representing malware behaviors including process execution and thread injection."},
    ],
}

# Apply alt texts to each file
for pptx_path, alts in files_alts.items():
    fixed_path = pptx_path.replace(".pptx", "_fixed.pptx")
    source = fixed_path if os.path.exists(fixed_path) else pptx_path
    result = apply_pptx_alt_texts(source, fixed_path, alts)
    size = os.path.getsize(fixed_path) if os.path.exists(fixed_path) else 0
    print(f"{os.path.basename(fixed_path)}: applied {result['applied']}/{result['total']} alt texts ({size:,} bytes)")

print("\nDone!")
