"""Phase 4b: Apply AI-generated alt texts to fixed PPTX/DOCX files.

Generic script — reads alt text JSON and applies to all files.
Replaces per-course apply scripts (apply_cyberinfra_alts.py, etc.).

Requires: data/alt_texts_{COURSE}.json (generated by AI agents)
          OR can read from data/images_needing_alt_{COURSE}.json with inline alt texts

Usage:
    python scripts/phase4b_apply_alts.py <course_key> <alt_texts_json>
    python scripts/phase4b_apply_alts.py CYBERINFRA data/alt_texts_CYBERINFRA.json
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(__file__))

from fix_office import apply_pptx_alt_texts, apply_docx_alt_texts, scan_pptx, scan_docx


def apply_all_alt_texts(alt_texts_path):
    """Apply alt texts from a JSON file to all referenced PPTX/DOCX files.

    Expected JSON format — list of entries:
    [
      {
        "fixed_path": "path/to/file_fixed.pptx",
        "alts": [
          {"slide": 11, "shape_idx": 2, "alt_text": "Description..."},
          ...
        ]
      },
      ...
    ]

    For DOCX files, alts should use {"index": 0, "alt_text": "..."} format.
    """
    with open(alt_texts_path) as f:
        data = json.load(f)

    results = []
    for entry in data:
        fixed_path = entry.get('fixed_path', '')
        if not fixed_path or not os.path.exists(fixed_path):
            # Try normalizing path
            fixed_path = fixed_path.replace('\\', '/').replace('/', os.sep)
            if not os.path.exists(fixed_path):
                print(f"  SKIP: File not found: {fixed_path}")
                continue

        alts = entry.get('alts', [])
        if not alts:
            continue

        ext = os.path.splitext(fixed_path)[1].lower()
        basename = os.path.basename(fixed_path)

        if ext == '.pptx':
            result = apply_pptx_alt_texts(fixed_path, fixed_path, alts)
        elif ext == '.docx':
            result = apply_docx_alt_texts(fixed_path, fixed_path, alts)
        else:
            print(f"  SKIP: Unsupported format for alt text: {basename}")
            continue

        print(f"  {basename}: applied {result['applied']}/{result['total']} alt texts")
        results.append({'file': basename, 'applied': result['applied'], 'total': result['total']})

    return results


def verify_no_missing_alts(alt_texts_path):
    """After applying, verify that files have no remaining images without alt text."""
    with open(alt_texts_path) as f:
        data = json.load(f)

    all_clear = True
    for entry in data:
        fixed_path = entry.get('fixed_path', '')
        if not os.path.exists(fixed_path):
            continue

        ext = os.path.splitext(fixed_path)[1].lower()
        basename = os.path.basename(fixed_path)

        if ext == '.pptx':
            issues = scan_pptx(fixed_path)
            remaining = issues.get('images_without_alt', 0)
        elif ext == '.docx':
            issues = scan_docx(fixed_path)
            remaining = issues.get('images_without_alt', 0)
        else:
            continue

        if remaining > 0:
            print(f"  WARNING: {basename} still has {remaining} images without alt text")
            all_clear = False

    return all_clear


def main():
    if len(sys.argv) < 3:
        print("Usage: python phase4b_apply_alts.py <course_key> <alt_texts_json>")
        print("  alt_texts_json: path to JSON file with alt texts")
        sys.exit(1)

    course_key = sys.argv[1].upper()
    alt_path = sys.argv[2]

    if not os.path.exists(alt_path):
        # Try in data directory
        from bb_utils import DATA_DIR
        alt_path = os.path.join(DATA_DIR, alt_path)

    if not os.path.exists(alt_path):
        print(f"ERROR: Alt texts file not found: {sys.argv[2]}")
        sys.exit(1)

    print(f"Phase 4b: Applying alt texts for {course_key}")
    results = apply_all_alt_texts(alt_path)

    total_applied = sum(r['applied'] for r in results)
    total_expected = sum(r['total'] for r in results)
    print(f"\nApplied {total_applied}/{total_expected} alt texts across {len(results)} files")

    # Verify
    print("\nVerifying...")
    if verify_no_missing_alts(alt_path):
        print("All files verified — no remaining images without alt text")
    else:
        print("WARNING: Some files still have images without alt text")


if __name__ == '__main__':
    main()
